import type { Koperasi } from "../types/gro-ai";

// TODO: Replace with API call when backend koperasi endpoint is ready
export const SAMPLE_KOPERASI: Koperasi[] = [
  {
    id: 1,
    name: "KSU Maju Gayo",
    komoditas: "Kopi Arabika",
    loc: "Aceh, Sumatera",
    volume: "2.4 Ton/bulan",
    targets: "Jepang & Singapura",
    cert: "GlobalGAP",
    price: "USD 4.20/kg",
    anggota: 342,
    bergabung: "Mar 2024",
    tags: ["Kopi Arabika", "Specialty Coffee", "Organik"],
    exportScore: 78,
    scoreBreakdown: { Sertifikasi: 90, Dokumen: 75, Regulasi: 70, Logistik: 65 },
  },
  {
    id: 2,
    name: "KUD Nelayan Makassar",
    komoditas: "Udang Vannamei",
    loc: "Makassar, Sulsel",
    volume: "5.8 Ton/bulan",
    targets: "Amerika & Jepang",
    cert: "HACCP",
    price: "USD 6.80/kg",
    anggota: 156,
    bergabung: "Jan 2024",
    tags: ["Udang Vannamei", "Seafood", "Frozen"],
    exportScore: 85,
    scoreBreakdown: { Sertifikasi: 95, Dokumen: 85, Regulasi: 80, Logistik: 80 },
  },
  {
    id: 3,
    name: "Koperasi Tani Sehat",
    komoditas: "Sayuran Organik",
    loc: "Bandung, Jawa Barat",
    volume: "1.2 Ton/bulan",
    targets: "Singapura & HK",
    cert: "Organik SNI",
    price: "USD 2.10/kg",
    anggota: 89,
    bergabung: "Jun 2024",
    tags: ["Sayuran Organik", "Hortikultura", "Fresh"],
    exportScore: 62,
    scoreBreakdown: { Sertifikasi: 80, Dokumen: 60, Regulasi: 55, Logistik: 50 },
  },
];
